spring:
  data:
    mongodb:
      uri: mongodb+srv://testuser:nlf2K6FU297rkKAG@cluster0.jzcp1cs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: customers
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.abe: INFO

