spring:
  data:
    mongodb:
      uri: mongodb+srv://abe:TmSlenDm3B221kRH@cluster0.jzcp1cs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: users
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.abe: INFO

