name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name bananagrenade5
          git config --global user.email 'bananagrenade5@gmail.com'
          git config --global credential.helper store  # Use credential helper to store access token

      - name: Increment Version
        id: increment-version
        run: |
          new_version=$(./scripts/increment_version.sh)
          echo "NEW_VERSION=$(echo $new_version)" >> $GITHUB_ENV

      - name: Commit Version Increment
        run: |
          echo $NEW_VERSION
          git status
          git add .
          git commit -m "Increment version to $NEW_VERSION"

      - name: Push Changes
        run: |
          git push origin main